CREATE TABLE DISTRITO (
    ID_DISTRITO NUMBER NOT NULL,
    NOMBRE VARCHAR2(5) NOT NULL,
    PRIMARY KEY (ID_DISTRITO)
);

-- MODIFICAR EL TAMANIO DEL CAMPO NOMBRE DE LA TABLA DISTRITO DE TAL MANERA QUE SU TAMANIO SEA 20
ALTER TABLE DISTRITO MODIFY NOMBRE VARCHAR2(20);

-- AGREGAR LA COLUMNA SUELDO DE TIPO NUMBER A LA TABLA PERSONA CON UN VALOR POR DEFECTO DE 1000
ALTER TABLE PERSONA ADD SUELDO NUMBER DEFAULT 1000;

-- AGREGAR EN LA TABLA PERSONA EL CAMPO ID_DISTRITO DE TIPO NUMBER
ALTER TABLE PERSONA ADD ID_DISTRITO NUMBER;

-- AGREGAR EN LA TABLA PERSONA EL CAMPO FECHA_NACIMIENTO DEL TIPO DATE
ALTER TABLE PERSONA ADD FECHA_NACIMIENTO DATE;

-- HACER QUE EL CAMPO ID_DISTRITO RECIEN ANIADIDO A LA TABLA PERSONA SEA UNA CLAVE FORANEA QUE HAGA REFERENCIA A LA TABLA DISTIRTO
ALTER TABLE PERSONA ADD FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO (ID_DISTRITO);

-- INSERTAR ALGUNOS DATOS EN LA TABLA DISTRITO
INSERT INTO DISTRITO (ID_DISTRITO, NOMBRE) VALUES (1, 'Miraflores');
INSERT INTO DISTRITO (ID_DISTRITO, NOMBRE) VALUES (2, 'Surco');
INSERT INTO DISTRITO (ID_DISTRITO, NOMBRE) VALUES (3, 'San Miguel');
INSERT INTO DISTRITO (ID_DISTRITO, NOMBRE) VALUES (4, 'San Borja');
INSERT INTO DISTRITO (ID_DISTRITO, NOMBRE) VALUES (5, 'Los Olivos');

-- MOSTRAR EL CONTENIDO DE LA TABLA DISTRITO
SELECT * FROM DISTRITO;

-- COPIAR EL CONTENIDO DEL ARCHIVO INF246_2020-1_LAB2_DIRIGIDA_inserts.sql EN LA HOJA DE TRABAJO Y EJECUTAR EL SCRIPT
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (1, 'Gómez', 'Casey', 'Leila', 'F', 3724.5, 3, to_date('24/02/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (2, 'Bennett', 'Montgomery', 'Bruno', 'M', 4407.5, 4, to_date('31/07/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (3, 'Brennan', 'Mckenzie', 'Paul', 'M', 1258.5, 4, to_date('16/07/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (4, 'Thomas', 'Mccall', 'Brett', 'M', 4336.5, 3, to_date('16/06/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (5, 'Mueller', 'Sheppard', 'Lev', 'M', 2396, 1, to_date('27/05/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (6, 'Ayala', 'Alford', 'Indigo', 'F', 4572, 3, to_date('30/10/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (7, 'Gillespie', 'Cole', 'Clark', 'M', 2792, 3, to_date('12/07/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (8, 'Harmon', 'Compton', 'Kiara', 'F', 4173.5, 5, to_date('23/03/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (9, 'Hanson', 'Hanson', 'Christine', 'F', 4606, 5, to_date('18/11/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (10, 'Dorsey', 'Mcclain', 'Aileen', 'F', 1513, 3, to_date('22/02/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (11, 'Luna', 'Rose', 'Homero', 'M', 2014, 5, to_date('31/03/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (12, 'Villarreal', 'Hall', 'Rajah', 'M', 1045.5, 5, to_date('20/05/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (13, 'Castro', 'Martinez', 'Lois', 'F', 1648, 4, to_date('13/02/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (14, 'Myers', 'Figueroa', 'Felicia', 'F', 1511.5, 2, to_date('11/08/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (15, 'Austin', 'Boone', 'Keith', 'M', 2112, 1, to_date('08/07/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (16, 'Jackson', 'Woodward', 'Irma', 'F', 2451, 4, to_date('10/11/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (17, 'Bailey', 'Moses', 'Isabella', 'F', 3305.5, 4, to_date('19/04/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (18, 'Moses', 'Lowery', 'Karen', 'F', 4622.5, 2, to_date('05/01/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (19, 'Miller', 'Best', 'Alden', 'M', 4716, 2, to_date('09/09/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (20, 'Hoffman', 'Vinson', 'Clint', 'M', 2088, 4, to_date('01/11/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (21, 'Rollins', 'Woodard', 'Lavinia', 'F', 1116.5, 5, to_date('04/11/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (22, 'Hopper', 'Thomas', 'Ruby', 'F', 4065, 2, to_date('03/06/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (23, 'Wolfe', 'Oneal', 'Ivana', 'F', 3521, 5, to_date('30/06/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (24, 'Beard', 'Baker', 'Phoebe', 'F', 4214, 2, to_date('25/12/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (25, 'Jacobs', 'Rhodes', 'Elmo', 'M', 4195.5, 3, to_date('07/08/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (26, 'Benson', 'Pierce', 'Ruth', 'F', 4077.5, 2, to_date('17/01/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (27, 'Sparks', 'Chan', 'Melanie', 'F', 3915.5, 1, to_date('25/10/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (28, 'Meyers', 'Bond', 'Rachel', 'F', 3915.5, 1, to_date('12/12/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (29, 'Keller', 'Mooney', 'Barry', 'M', 3649.5, 2, to_date('04/06/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (30, 'Middleton', 'Travis', 'Chadwick', 'M', 1414, 1, to_date('22/03/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (31, 'Montoya', 'Dorsey', 'Megan', 'F', 1983.5, 5, to_date('21/06/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (32, 'Stanley', 'Gamble', 'Dale', 'M', 2197, 4, to_date('08/09/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (33, 'Hartman', 'Durham', 'Alex', 'M', 3543, 5, to_date('20/01/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (34, 'Trujillo', 'Wyatt', 'Ila', 'F', 3444.5, 4, to_date('23/01/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (35, 'Allen', 'Jensen', 'Dylan', 'M', 3603.5, 1, to_date('18/11/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (36, 'Hinton', 'Glenn', 'Tyrone', 'M', 3471, 2, to_date('29/05/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (37, 'Brewer', 'Davidson', 'Joel', 'M', 3617.5, 5, to_date('11/08/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (38, 'Singleton', 'Conley', 'Brittany', 'F', 2322.5, 5, to_date('15/12/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (39, 'Landry', 'Sanders', 'April', 'F', 3757, 3, to_date('14/04/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (40, 'Rowland', 'Mccoy', 'Erick', 'M', 3582, 1, to_date('15/09/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (41, 'Burton', 'Hays', 'Michael', 'M', 1348, 4, to_date('22/10/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (42, 'Eaton', 'Reed', 'Troy', 'M', 3598.5, 2, to_date('15/08/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (43, 'Ford', 'McFadden', 'Harrison', 'M', 3534.5, 4, to_date('02/02/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (44, 'Montgomery', 'Joyner', 'Robert', 'M', 1684, 3, to_date('19/01/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (45, 'Bradford', 'Barber', 'Gwendolyn', 'F', 1659, 1, to_date('06/09/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (46, 'Wall', 'Moon', 'Wesley', 'M', 4604, 2, to_date('05/09/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (47, 'Hooper', 'James', 'Riley', 'F', 1817.5, 3, to_date('26/02/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (48, 'Hines', 'Petersen', 'Veronica', 'F', 1599, 5, to_date('16/03/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (49, 'Henderson', 'Jones', 'Vilma', 'F', 3172.5, 3, to_date('16/10/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (50, 'Fitzgerald', 'Maxwell', 'Jolie', 'F', 4953.5, 1, to_date('30/03/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (51, 'Nguyen', 'Ramirez', 'Mark', 'M', 2535.5, 5, to_date('07/06/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (52, 'Alvarez', 'Beach', 'Thaddeus', 'M', 1765, 2, to_date('05/11/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (53, 'Grant', 'Woods', 'Raymond', 'M', 3515.5, 1, to_date('03/05/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (54, 'Montana', 'Dawson', 'Hanna', 'F', 2267.5, 2, to_date('18/04/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (55, 'Rivers', 'Hardy', 'Neil', 'M', 4337, 3, to_date('28/12/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (56, 'Horne', 'Lancaster', 'Hall', 'M', 2509, 3, to_date('22/06/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (57, 'Lara', 'Mcmahon', 'Erika', 'F', 1073, 4, to_date('05/04/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (58, 'Smith', 'Beasley', 'Allistair', 'M', 4795, 2, to_date('15/06/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (59, 'Daniels', 'Good', 'Maya', 'F', 4034.5, 1, to_date('01/04/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (60, 'Franklin', 'Rivera', 'Octavia', 'F', 2587.5, 3, to_date('13/02/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (61, 'Mccall', 'Serrano', 'Lana', 'F', 3498.5, 4, to_date('01/07/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (62, 'Pickett', 'Hicks', 'Zelda', 'F', 4562, 3, to_date('31/10/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (63, 'Gilliam', 'Gould', 'Zane', 'M', 4068, 3, to_date('30/07/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (64, 'Winters', 'Tanner', 'Seth', 'M', 4787.5, 3, to_date('04/04/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (65, 'Beck', 'Newman', 'Felix', 'M', 3228.5, 1, to_date('11/03/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (66, 'Bray', 'Mcleod', 'Blake', 'M', 2039.5, 2, to_date('03/06/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (67, 'Compton', 'Carr', 'Regina', 'F', 2637.5, 1, to_date('26/03/2001', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (68, 'Sellers', 'Carey', 'Vivian', 'F', 4525, 1, to_date('13/06/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (69, 'Russell', 'Joyce', 'Jenette', 'F', 1031, 4, to_date('12/08/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (70, 'Hodges', 'Carpenter', 'Caleb', 'M', 1254, 3, to_date('14/10/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (71, 'Hoffman', 'Stein', 'Yvette', 'F', 3925, 5, to_date('11/07/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (72, 'Murray', 'Smith', 'Esmeralda', 'F', 4975.5, 2, to_date('10/02/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (73, 'Humphrey', 'Howard', 'Abraham', 'M', 4266, 5, to_date('24/03/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (74, 'Byrd', 'Flowers', 'Gloria', 'F', 4232.5, 2, to_date('07/06/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (75, 'Abbott', 'Campos', 'Octavius', 'M', 1682.5, 1, to_date('11/10/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (76, 'Salas', 'Núñez', 'Cassandra', 'F', 3702, 5, to_date('18/09/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (77, 'Conley', 'Finley', 'Ivan', 'M', 2749, 3, to_date('21/11/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (78, 'Barrera', 'Mcbride', 'Esperanza', 'F', 1093, 3, to_date('03/11/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (79, 'Harmon', 'Goodman', 'Barrett', 'M', 1031, 2, to_date('13/01/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (80, 'Harrington', 'Gordon', 'Nina', 'F', 4324, 4, to_date('14/01/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (81, 'Park', 'Randall', 'Yasir', 'M', 4269, 5, to_date('24/01/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (82, 'Weeks', 'Chambers', 'Akeem', 'M', 4094, 1, to_date('03/03/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (83, 'Camacho', 'Knapp', 'Montana', 'F', 1703.5, 2, to_date('13/11/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (84, 'Hughes', 'Newton', 'Noah', 'M', 4455.5, 3, to_date('12/10/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (85, 'Garner', 'Branch', 'Destiny', 'F', 2332, 4, to_date('14/08/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (86, 'Wheeler', 'Lynch', 'Katty', 'F', 3930, 3, to_date('16/01/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (87, 'George', 'Bolton', 'Virginia', 'F', 3680.5, 3, to_date('18/10/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (88, 'Love', 'Workman', 'Kim', 'F', 1070.5, 2, to_date('25/05/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (89, 'Weber', 'Alford', 'Damián', 'M', 3268.5, 4, to_date('19/10/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (90, 'Benton', 'Armstrong', 'Jerry', 'M', 3444.5, 2, to_date('23/07/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (91, 'Michael', 'Stuart', 'Vivian', 'F', 3595, 3, to_date('11/06/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (92, 'Lester', 'Beach', 'Angelica', 'F', 1077.5, 1, to_date('11/03/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (93, 'Everett', 'Gibson', 'Lacy', 'F', 4428.5, 2, to_date('07/10/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (94, 'Mcpherson', 'Acevedo', 'May', 'F', 4508.5, 2, to_date('28/01/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (95, 'Peters', 'Benson', 'Harriet', 'F', 4964, 5, to_date('13/07/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (96, 'Alston', 'Abbott', 'Jane', 'F', 2250, 4, to_date('30/12/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (97, 'Gilmore', 'Clark', 'Athena', 'F', 4370, 4, to_date('17/02/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (98, 'Morales', 'Snow', 'Garrison', 'M', 4577, 2, to_date('17/11/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (99, 'Ciccone', 'Fortin', 'Madonna', 'F', 4015.5, 1, to_date('19/10/2003', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (100, 'Gómez', 'Bradley', 'Edward', 'M', 2182.5, 2, to_date('05/10/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (101, 'Mann', 'Nelson', 'Abel', 'M', 3736.5, 1, to_date('03/01/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (102, 'Faulkner', 'Roberson', 'Myra', 'F', 4283.5, 2, to_date('05/05/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (103, 'Harrell', 'Jefferson', 'Henry', 'M', 4752.5, 5, to_date('16/06/2000', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (104, 'Garrett', 'Figueroa', 'Rubén', 'M', 3599.5, 4, to_date('19/01/1998', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (105, 'Norton', 'Ortega', 'Jared', 'M', 2820.5, 2, to_date('17/03/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (106, 'Herring', 'Schwartz', 'Indira', 'F', 1582.5, 1, to_date('22/07/1999', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (107, 'Muñoz', 'Haney', 'Richard', 'M', 1508.5, 3, to_date('18/07/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (108, 'Johns', 'Olsen', 'Eric', 'M', 2291.5, 3, to_date('20/05/1996', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (109, 'Ono', 'Lennon', 'Yoko', 'F', 2288.5, 4, to_date('25/12/2005', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (110, 'Harrison', 'Sampson', 'Grace', 'F', 3150.5, 1, to_date('15/10/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (111, 'Barton', 'Humphrey', 'Leroy', 'M', 3484.5, 4, to_date('16/01/2004', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (112, 'Guzman', 'Merrill', 'Blake', 'M', 4513.5, 1, to_date('23/09/1997', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (113, 'Goodwin', 'Camacho', 'Rebekah', 'F', 1039, 3, to_date('11/10/2002', 'dd/mm/yyyy'));
INSERT INTO PERSONA (ID_PERSONA, APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, SUELDO, ID_DISTRITO, FECHA_NACIMIENTO) VALUES (114, 'Juárez', 'Henderson', 'Karen', 'F', 3887, 1, to_date('03/04/2003', 'dd/mm/yyyy'));

-- MOSTRAR EL CONTENIDO DE LA TABLA PERSONA
SELECT * FROM PERSONA;

-- MOSTRAR LOS APELLIDOS Y NOMBRE DE LAS PERSONAS, ORDENADAS POR APELLIDO PATERNO
SELECT APE_PATERNO, APE_MATERNO, NOMBRE
FROM PERSONA
ORDER BY APE_PATERNO;

-- MOSTRAR APELLIDOS, NOMBRES Y SUELDO DE TODAS LAS PERSONAS DE SEXO FEMENINO, ORDENADAS POR EL SUELDO DE FORMA DESCENDIENTE. SI HAY SUELDOS IGUALES, ORDENAR POR APELLIDO PATERNO DE FORMA ASCENDENTE
SELECT APE_PATERNO, APE_MATERNO, NOMBRE, SUELDO
FROM PERSONA
WHERE SEXO = 'F'
ORDER BY SUELDO DESC, APE_PATERNO ASC;

-- MOSTRAR LOS APELLIDOS Y NOMBRES CONCATENADOS CON ESPACIOS Y COMAS, Y EL SUELDO DE TODAS LAS PERSONAS DE SEXO MASCULINO
SELECT APE_PATERNO || ' ' || APE_MATERNO || ', ' || NOMBRE AS NOMBRE_COMPLETO, SUELDO
FROM PERSONA
WHERE SEXO = 'M';

-- MOSTRAR LOS APELLIDOS, NOMBRE, SEXO, FECHA DE NACIMIENTO, ORDENADOS ASCENDENTEMENTE POR FECHA DE NACIMIENTO
SELECT APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, TO_CHAR(FECHA_NACIMIENTO, 'DD/MM/YYYY') AS FECHANACIMIENTO
FROM PERSONA
ORDER BY FECHA_NACIMIENTO ASC;

-- MOSTRAR LOS APELLIDOS, NOMBRE, SEXO, FECHA DE NACIMIENTO (DD/MM) DE LAS PERSONAS QUE NACIERON EN EL ANIO 2000, ORDENADOS ALFABETICAMENTE POR EL APELLIDO PATERNO
SELECT APE_PATERNO, APE_MATERNO, NOMBRE, SEXO, TO_CHAR(FECHA_NACIMIENTO, 'DD/MM') AS DIA_MES
FROM PERSONA
WHERE FECHA_NACIMIENTO BETWEEN TO_DATE('01/01/2000', 'DD/MM/YYYY') AND TO_DATE('31/12/2000', 'DD/MM/YY')
ORDER BY APE_PATERNO ASC;

-- MOSTRAR LOS APELLIDOS, NOMBRE Y SEXO DE LAS PERSONAS, Y LOS DISTRITOS DONDE VIVEN ORDENADOS ALFABETICAMENTE POR EL NOMBRE DEL DISTRITO
SELECT APE_PATERNO, APE_MATERNO, P.NOMBRE, SEXO, D.NOMBRE
FROM PERSONA P, DISTRITO D
WHERE P.ID_DISTRITO = D.ID_DISTRITO
ORDER BY D.NOMBRE ASC;

-- MOSTRAR LOS APELLIDOS Y NOMBRES DE LAS MUJERES QUE VIVEN EN SURCO
SELECT P.APE_PATERNO, P.APE_MATERNO, P.NOMBRE
FROM PERSONA P, DISTRITO D
WHERE P.SEXO = 'F' AND P.ID_DISTRITO = D.ID_DISTRITO AND D.NOMBRE = 'Surco';

-- MOSTRAR EL NOMBRE COMPLETO DE LAS PERSONAS QUE NACIERON EN EL ANIO 2000 Y QUE VIVEN EN SURCO
SELECT P.APE_PATERNO || ' ' || P.APE_MATERNO || ', ' || P.NOMBRE AS NOMBRE_COMPLETO
FROM PERSONA P, DISTRITO D
WHERE P.ID_DISTRITO = D.ID_DISTRITO AND D.NOMBRE = 'Surco' AND FECHA_NACIMIENTO BETWEEN TO_DATE('01/01/2000', 'DD/MM/YYYY') AND TO_DATE('31/12/2000', 'DD/MM/YY');

-- MOSTRAR EL NOMBRE COMPLETO DE LAS PERSONAS CUYO APELLIDO PATERNO EMPIEZA CON LA LETRA B, Y SU SUELDO EN SOLES. CONSIDERAR UNA TASA DE CAMBIO DE 3.40 SOLES POR CADA DOLAR
SELECT P.APE_PATERNO || ' ' || P.APE_MATERNO || ', ' || P.NOMBRE AS NOMBRE_COMPLETO, P.SUELDO * 3.4 AS SUELDO_SOLES
FROM PERSONA P
WHERE P.APE_PATERNO LIKE 'B%';

-- INCREMENTAR EN 100 DOLARES EL SUELDO DE LAS PERSONAS QUE GANAN ENTRE 1000 Y 2000 DOLARES
UPDATE PERSONA
SET SUELDO = SUELDO + 100
WHERE SUELDO BETWEEN 1000 AND 2000;

-- ACTUALIZAR EL SUELDO DE LAS PERSONAS QUE GANAN MAS DE 4800 DOLARES, DESCONTANDOLES EL 5% DEL SUELDO
UPDATE PERSONA
SET SUELDO = 95 * SUELDO / 100
WHERE SUELDO > 4800;

-- MOSTRAR LA SUMA DE SUELDOS, PROMEDIO DE SUELDOS, SUELDO MAXIMO Y SUELDO MINIMO DE TODAS LAS PERSONAS
SELECT SUM(SUELDO), AVG(SUELDO), MAX(SUELDO), MIN(SUELDO)
FROM PERSONA;

-- MOSTRAR LA CANTIDAD DE VARONES QUE GANAN MAS DE 3000 DOLARES
SELECT COUNT(*)
FROM PERSONA
WHERE SEXO = 'M' AND SUELDO > 3000;

-- ELIMINAR LOS DATOS DE LAS PERSONAS QUE GANAN MAS DE 4500 DOLARES
DELETE FROM PERSONA
WHERE SUELDO > 4500;

-- ELIMINAR LOS DATOS DE LAS PERSONAS QUE NACIERON EN EL ANIO 1996
DELETE FROM PERSONA
WHERE FECHA_NACIMIENTO BETWEEN TO_DATE('01/01/1996', 'DD/MM/YYYY') AND TO_DATE('31/12/1996', 'DD/MM/YYYY');