BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CARGOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMPLEADOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ESTUDIOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HISTORIAL_LABORAL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HISTORIAL_SALARIAL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TRABAJOS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE UNIVERSIDADES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF sqlcode != -942 THEN
            RAISE;
        END IF;
END;
/